#!/usr/bin/env bash

. "${BASH_SOURCE[0]%/*}/easypap-utilities.bash"

if [ $# != 1 ]; then
    echo "Usage: ${BASH_SOURCE[0]##*/} <kernel>"
    exit 1
fi

_easypap_variants "$1" || exit 1
echo $variants

exit 0
