#!/usr/bin/env bash

. "${BASH_SOURCE%/*}/easypap-utilities.bash"

if [ $# != 1 ]; then
    echo "Usage: ${0##*/} <kernel>"
    exit 1
fi

_easypap_gpu_variants "$1" || exit 1
echo $gvariants

exit 0
